Implementation of MYS-223
- Removing Unicode support.
- DLL-Exporting some members from Python_context.
- Samples updated to show how to invoke Python mode.
- Some updates in samples/native/README.txt sample session.
- Install script now also deploys python dependencies.
- Py_NoSiteFlag set in Windows build (to avoid dependencies on env variables PYTHON_HOME)
- On shell's main.cc moved declaration "void Python_context_init();" out of function, to avoid
  error C2598: linkage specification must be at global scope

rb9567, rennox