BUG#37892879 Dump should report partitioned tables without a primary key as errors
When running a dump with the `create_invisible_pks` compatibility option
set, Shell did not report partitioned tables without primary keys as
errors, as in this case PK cannot be added automatically:

  All columns used in the partitioning expression for a partitioned
  table must be part of every unique key that the table may have.

Such tables are now reported as errors:

  ERROR: Table `s`.`t` does not have a Primary Key, this cannot be fixed
  automatically because the table is partitioned (this issue needs to be
  fixed manually)

Change-Id: Ia7b79fd10e7c8d5f3077f871d7d2a14849a93db9