BUG#34206985 dumpInstance on mariadb 10.4 fails with error during chunking
Dumping an instance in mariadb 10.4.18 failed with the following error
during chunking:

  ERROR: [Worker004]: Error while chunking `xxxx`.`xxxx`: get_uint(8): field type is String

As a fix, the output of EXPLAIN SELECT statement is fetched as a string
and converted to an unsigned integer.

Change-Id: I02933e2b767ba58930cd2bd11ce05b84030dea4e