Refactoring Session API Objects to replace add_method() to expose()
The legacy add_method() function used to expose functions into the API objects needs
to be replaced by the new expose() function.

This patch does this update in the following API Objects:

- mysqlx.Session
- mysqlx.SqlExecute
- mysql.ClassicSession

TODO: Using expose on the __shell_hook__ causes errors to prepend the __shell_hook__
name into them, this will be resolved before merging this patch.

EXAMPLE:

mysql-js []> session.sql("whatever")
ERROR: 1064: SqlExecute.__shell_hook__: You have an error in your SQL syntax;

Change-Id: Ibb98b045af7440385bcdd4b09d0521fd164d3ebb