BUG#36552764 Update the list of allowed authentication plugins
The following changes have been applied to the list of allowed
authentication plugins when dumping with 'ocimds':true:

 - the 'authentication_oci' plugin is allowed
 - if 'targetVersion' is set to >= '9.0.0':
     the 'mysql_native_password' plugin is disallowed
   else:
     the 'mysql_native_password' plugin is reported as deprecated
 - the 'sha256_password' plugin is reported as deprecated

When loading into MHS, if a CREATE USER statement fails with:
  ERROR: 1524 (HY000): Plugin '%s' is not loaded
the error is ignored, a warning is displayed, and loading continues.

The following privileges have been added to the list of privileges
allowed in MHS:
  - PROXY
  - SHOW_ROUTINE

Change-Id: Ieba83a2f0aa9e3a4e84fa48bfdc5efbb9ef2a623