Bug#35023480 shell cannot connect if both port and socket file/named path specified
Old validations for conflicting socket and port options was preventing
these options from being used in my.cnf

Overzealous validations were removed and the new rule where
conflicts are resolved by making the last value take precedence
applies.

Also fixes "mysqlsh -uroot -S" producing
ERROR: Failed to retrieve the password: Invalid URL: Invalid address

Change-Id: Iac83e6dc8ec1f4afca1938b0eadcac295e81c04a